/**
 * autoGeneratedIds.test.js — POST /edit/stops, /edit/routes and /edit/trips
 * generate a server-side id when the id field is absent or empty.
 */

"use strict";

const {
  seedSession,
  teardownSession,
  removeUploadRoot,
  api,
} = require("./_helpers/sampleSession");

describe("auto-generated ids on create", () => {
  let sessionId;
  let db;

  beforeAll(async () => {
    ({ sessionId, db } = await seedSession());
  }, 60_000);

  afterAll(() => {
    teardownSession(sessionId);
    removeUploadRoot();
  });

  test("POST /edit/stops without stop_id", async () => {
    const first = await api(sessionId).post("/edit/stops", {
      stop_name: "Generated stop",
      stop_lat: 40.71,
      stop_lon: -74.0,
    });
    expect(first.status).toBe(201);
    expect(first.body.id_generated).toBe(true);
    const id1 = first.body.stop.stop_id;
    expect(id1).toMatch(/^(S\d+|stop_[0-9a-f]{6})$/);
    expect(db.prepare("SELECT stop_name FROM stops WHERE stop_id = ?").get(id1).stop_name).toBe("Generated stop");

    // Empty string behaves like absent; ids never collide.
    const second = await api(sessionId).post("/edit/stops", {
      stop_id: "",
      stop_name: "Generated stop 2",
      stop_lat: 40.72,
      stop_lon: -74.01,
    });
    expect(second.status).toBe(201);
    expect(second.body.stop.stop_id).not.toBe(id1);

    // Numeric feeds: S + zero-padded next number.
    db.prepare("INSERT INTO stops (stop_id, stop_name, stop_lat, stop_lon) VALUES ('0042', 'Numeric', 40.7, -74)").run();
    const third = await api(sessionId).post("/edit/stops", {
      stop_name: "Generated stop 3",
      stop_lat: 40.73,
      stop_lon: -74.02,
    });
    expect(third.status).toBe(201);
    expect(third.body.stop.stop_id).toBe("S0043");

    // Explicit ids keep the old behaviour (incl. 409 on duplicates).
    const explicit = await api(sessionId).post("/edit/stops", {
      stop_id: "EXPLICIT_1",
      stop_name: "Explicit",
      stop_lat: 40.7,
      stop_lon: -74,
    });
    expect(explicit.status).toBe(201);
    expect(explicit.body.id_generated).toBe(false);
    expect(explicit.body.stop.stop_id).toBe("EXPLICIT_1");
    const dup = await api(sessionId).post("/edit/stops", {
      stop_id: "EXPLICIT_1",
      stop_name: "Explicit",
      stop_lat: 40.7,
      stop_lon: -74,
    });
    expect(dup.status).toBe(409);
  });

  test("POST /edit/routes without route_id → R_<slug>, de-duplicated", async () => {
    const first = await api(sessionId).post("/edit/routes", {
      route_short_name: "X 9",
      route_long_name: "Generated route",
      route_type: 3,
    });
    expect(first.status).toBe(201);
    expect(first.body.id_generated).toBe(true);
    expect(first.body.route.route_id).toBe("R_X_9");

    const second = await api(sessionId).post("/edit/routes", {
      route_id: "",
      route_short_name: "X 9",
      route_type: 3,
    });
    expect(second.status).toBe(201);
    expect(second.body.route.route_id).toBe("R_X_9_2");

    const third = await api(sessionId).post("/edit/routes", { route_short_name: "X 9", route_type: 3 });
    expect(third.body.route.route_id).toBe("R_X_9_3");

    // No short name → long name slug; nothing at all → random suffix.
    const longOnly = await api(sessionId).post("/edit/routes", {
      route_long_name: "Cross Town",
      route_type: 3,
    });
    expect(longOnly.body.route.route_id).toBe("R_Cross_Town");
    const bare = await api(sessionId).post("/edit/routes", { route_type: 3 });
    expect(bare.status).toBe(201);
    expect(bare.body.route.route_id).toMatch(/^R_[0-9a-f]{6}$/);

    // route_type is still required.
    expect((await api(sessionId).post("/edit/routes", { route_short_name: "Z" })).status).toBe(400);
  });

  test("POST /edit/trips without trip_id → <route_id>_<direction or 0>_<n>", async () => {
    const first = await api(sessionId).post("/edit/trips", {
      route_id: "S1",
      service_id: "WKD",
      direction_id: "1",
    });
    expect(first.status).toBe(201);
    expect(first.body.id_generated).toBe(true);
    expect(first.body.trip.trip_id).toMatch(/^S1_1_\d{3}$/);

    const second = await api(sessionId).post("/edit/trips", {
      trip_id: "",
      route_id: "S1",
      service_id: "WKD",
      direction_id: "1",
    });
    expect(second.status).toBe(201);
    expect(second.body.trip.trip_id).toMatch(/^S1_1_\d{3}$/);
    expect(second.body.trip.trip_id).not.toBe(first.body.trip.trip_id);

    const noDirection = await api(sessionId).post("/edit/trips", {
      route_id: "S1",
      service_id: "WKD",
    });
    expect(noDirection.status).toBe(201);
    expect(noDirection.body.trip.trip_id).toMatch(/^S1_0_\d{3}$/);

    // route_id / service_id stay mandatory.
    expect((await api(sessionId).post("/edit/trips", { service_id: "WKD" })).status).toBe(400);
  });
});
