/**
 * documentsService — passenger-facing documents from the loaded feed.
 *
 *   GET /gtfs/documents/timetable?route_id=&date=&lang=   → HTML, print-ready
 *   GET /gtfs/documents/stop?stop_id=&date=&lang=         → HTML, print-ready
 *
 * The line timetable: for each direction, the stops in order and the
 * departures of the day — as a matrix (stops × trips) when the line runs
 * fewer than 30 trips, else in the classic "hour : minutes" grid of a
 * frequent line. The stop poster: for each line and direction serving the
 * stop, the hour : minutes grid of the day, first and last departure.
 * Frequencies expand into explicit departures. When the requested date has
 * no service, the next day with service (within 14 days) is used and
 * said. Everything is inline HTML/CSS: it prints as it shows.
 */

"use strict";

const { requireSession } = require("./edit/_editCore");
const { getServiceIdsForDate } = require("./calendarService");

const MATRIX_MAX_TRIPS = 30;
const MAX_TRIPS = 4000;
const MAX_FREQ_DEPARTURES = 300;
const LOOKAHEAD_DAYS = 14;

const L10N = {
  en: { timetable: "Timetable", poster: "Departures", direction: "Towards", validOn: "Valid on", nextService: "No service on the requested date; showing", firstLast: "First / last", hour: "Hour", minutes: "Minutes", noService: "No service that day.", generated: "Generated by GTFS Express", trips: "trips", line: "Line", stop: "Stop", days: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"] },
  fr: { timetable: "Fiche horaire", poster: "Départs", direction: "Direction", validOn: "Valable le", nextService: "Pas de service à la date demandée ; affichage du", firstLast: "Premier / dernier", hour: "Heure", minutes: "Minutes", noService: "Pas de service ce jour.", generated: "Généré par GTFS Express", trips: "courses", line: "Ligne", stop: "Arrêt", days: ["dim.", "lun.", "mar.", "mer.", "jeu.", "ven.", "sam."] },
  es: { timetable: "Horario", poster: "Salidas", direction: "Dirección", validOn: "Válido el", nextService: "Sin servicio en la fecha pedida; se muestra el", firstLast: "Primero / último", hour: "Hora", minutes: "Minutos", noService: "Sin servicio ese día.", generated: "Generado por GTFS Express", trips: "viajes", line: "Línea", stop: "Parada", days: ["dom", "lun", "mar", "mié", "jue", "vie", "sáb"] },
  de: { timetable: "Fahrplan", poster: "Abfahrten", direction: "Richtung", validOn: "Gültig am", nextService: "Kein Betrieb am gewünschten Tag; angezeigt wird der", firstLast: "Erste / letzte", hour: "Stunde", minutes: "Minuten", noService: "Kein Betrieb an diesem Tag.", generated: "Erstellt mit GTFS Express", trips: "Fahrten", line: "Linie", stop: "Haltestelle", days: ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"] },
  pt: { timetable: "Horário", poster: "Partidas", direction: "Sentido", validOn: "Válido a", nextService: "Sem serviço na data pedida; mostra-se", firstLast: "Primeira / última", hour: "Hora", minutes: "Minutos", noService: "Sem serviço nesse dia.", generated: "Gerado por GTFS Express", trips: "viagens", line: "Linha", stop: "Paragem", days: ["dom", "seg", "ter", "qua", "qui", "sex", "sáb"] },
  zh: { timetable: "时刻表", poster: "发车时刻", direction: "开往", validOn: "有效日期", nextService: "所选日期无服务，显示", firstLast: "首班 / 末班", hour: "小时", minutes: "分钟", noService: "当天无服务。", generated: "由 GTFS Express 生成", trips: "班次", line: "线路", stop: "站点", days: ["日", "一", "二", "三", "四", "五", "六"] },
  ar: { timetable: "جدول المواعيد", poster: "المغادرات", direction: "باتجاه", validOn: "ساري في", nextService: "لا خدمة في التاريخ المطلوب؛ يُعرض", firstLast: "الأول / الأخير", hour: "الساعة", minutes: "الدقائق", noService: "لا خدمة في ذلك اليوم.", generated: "أُنشئ بواسطة GTFS Express", trips: "رحلات", line: "الخط", stop: "المحطة", days: ["أحد", "اثنين", "ثلاثاء", "أربعاء", "خميس", "جمعة", "سبت"] },
  hi: { timetable: "समय-सारणी", poster: "प्रस्थान", direction: "की ओर", validOn: "मान्य तिथि", nextService: "अनुरोधित तिथि पर सेवा नहीं; दिखाया जा रहा है", firstLast: "पहली / अंतिम", hour: "घंटा", minutes: "मिनट", noService: "उस दिन सेवा नहीं।", generated: "GTFS Express द्वारा निर्मित", trips: "ट्रिप", line: "लाइन", stop: "स्टॉप", days: ["रवि", "सोम", "मंगल", "बुध", "गुरु", "शुक्र", "शनि"] },
};

const esc = (s) => String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]);
const parseTime = (t) => {
  const m = /^(\d{1,2}):(\d{2})(?::(\d{2}))?$/.exec(String(t || "").trim());
  return m ? parseInt(m[1], 10) * 3600 + parseInt(m[2], 10) * 60 + (m[3] ? parseInt(m[3], 10) : 0) : null;
};
const hhmm = (s) => `${String(Math.floor(s / 3600)).padStart(2, "0")}:${String(Math.floor((s % 3600) / 60)).padStart(2, "0")}`;
const todayYmd = () => {
  const d = new Date();
  return `${d.getUTCFullYear()}${String(d.getUTCMonth() + 1).padStart(2, "0")}${String(d.getUTCDate()).padStart(2, "0")}`;
};
const addDays = (ymd, n) => {
  const d = new Date(Date.UTC(+ymd.slice(0, 4), +ymd.slice(4, 6) - 1, +ymd.slice(6, 8) + n));
  return `${d.getUTCFullYear()}${String(d.getUTCMonth() + 1).padStart(2, "0")}${String(d.getUTCDate()).padStart(2, "0")}`;
};
const prettyDate = (ymd, l) => {
  const d = new Date(Date.UTC(+ymd.slice(0, 4), +ymd.slice(4, 6) - 1, +ymd.slice(6, 8)));
  return `${l.days[d.getUTCDay()]} ${ymd.slice(6, 8)}/${ymd.slice(4, 6)}/${ymd.slice(0, 4)}`;
};
const textColorFor = (hex) => {
  const h = /^[0-9A-Fa-f]{6}$/.test(hex || "") ? hex : "1E88E5";
  const r = parseInt(h.slice(0, 2), 16);
  const g = parseInt(h.slice(2, 4), 16);
  const b = parseInt(h.slice(4, 6), 16);
  return (0.299 * r + 0.587 * g + 0.114 * b) / 255 > 0.6 ? "111111" : "FFFFFF";
};

/** The service ids of a date, or of the next date with service within LOOKAHEAD_DAYS. */
const resolveServiceDate = (db, date) => {
  const calendar = db.prepare("SELECT * FROM calendar").all();
  const calendarDates = db.prepare("SELECT service_id, date, exception_type FROM calendar_dates").all();
  for (let i = 0; i <= LOOKAHEAD_DAYS; i++) {
    const d = addDays(date, i);
    const ids = getServiceIdsForDate(d, calendar, calendarDates);
    if (ids.length) return { date: d, requested: date, shifted: i > 0, services: new Set(ids) };
  }
  return { date, requested: date, shifted: false, services: new Set() };
};

/** Trips of the day for a route (or all routes when routeId is null): [{trip_id, route_id, direction_id, headsign, stops:[{stop_id, dep}]}]. */
const dayTrips = (db, services, { routeId = null, stopId = null } = {}) => {
  const where = routeId ? "WHERE t.route_id = ?" : "";
  const trips = new Map();
  for (const t of db.prepare(`SELECT t.trip_id, t.route_id, t.service_id, t.direction_id, t.trip_headsign FROM trips t ${where}`).iterate(...(routeId ? [routeId] : []))) {
    if (!services.has(t.service_id)) continue;
    trips.set(t.trip_id, { trip_id: t.trip_id, route_id: t.route_id, direction_id: t.direction_id === "1" ? "1" : "0", headsign: t.trip_headsign || "", stops: [] });
    if (trips.size > MAX_TRIPS) break;
  }
  if (!trips.size) return [];
  const ids = [...trips.keys()];
  const chunk = 500;
  for (let i = 0; i < ids.length; i += chunk) {
    const part = ids.slice(i, i + chunk);
    const rows = db.prepare(`SELECT trip_id, stop_id, arrival_time, departure_time, stop_sequence FROM stop_times WHERE trip_id IN (${part.map(() => "?").join(",")}) ORDER BY trip_id, CAST(stop_sequence AS INTEGER)`).all(...part);
    for (const r of rows) trips.get(r.trip_id).stops.push({ stop_id: r.stop_id, dep: parseTime(r.departure_time || r.arrival_time) });
  }
  // Frequencies: expand into explicit departures.
  const freqs = new Map();
  try {
    for (const f of db.prepare("SELECT trip_id, start_time, end_time, headway_secs FROM frequencies").iterate()) {
      if (!trips.has(f.trip_id)) continue;
      const s = parseTime(f.start_time);
      const e = parseTime(f.end_time);
      const h = parseInt(f.headway_secs, 10);
      if (s == null || e == null || !(h > 0)) continue;
      if (!freqs.has(f.trip_id)) freqs.set(f.trip_id, []);
      freqs.get(f.trip_id).push({ start: s, end: e, headway: h });
    }
  } catch {
    /* no frequencies table */
  }
  const out = [];
  for (const t of trips.values()) {
    if (t.stops.length < 2 || t.stops[0].dep == null) continue;
    if (stopId && !t.stops.some((s) => s.stop_id === stopId)) continue;
    const fr = freqs.get(t.trip_id);
    if (!fr) {
      out.push(t);
      continue;
    }
    const first = t.stops[0].dep;
    for (const f of fr) {
      let k = 0;
      for (let x = f.start; x < f.end && k < MAX_FREQ_DEPARTURES; x += f.headway, k++) out.push({ ...t, trip_id: `${t.trip_id}@${hhmm(x)}`, stops: t.stops.map((s) => ({ stop_id: s.stop_id, dep: s.dep == null ? null : s.dep + (x - first) })) });
    }
  }
  return out;
};

/** Hour → sorted minutes grid of a list of departure seconds. */
const hourGrid = (deps) => {
  const byHour = new Map();
  for (const s of deps) {
    const h = Math.floor(s / 3600);
    if (!byHour.has(h)) byHour.set(h, []);
    byHour.get(h).push(Math.floor((s % 3600) / 60));
  }
  return [...byHour.entries()].sort((a, b) => a[0] - b[0]).map(([h, mins]) => [h, [...new Set(mins)].sort((a, b) => a - b)]);
};

const CSS = `
  * { box-sizing: border-box; }
  body { font-family: -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; margin: 0; color: #111; background: #fff; }
  .page { padding: 18mm 14mm; max-width: 297mm; margin: 0 auto; }
  .head { display: flex; align-items: center; gap: 12px; margin-bottom: 10px; }
  .badge { min-width: 46px; height: 46px; border-radius: 12px; display: flex; align-items: center; justify-content: center; font-weight: 800; font-size: 20px; padding: 0 10px; }
  h1 { font-size: 22px; margin: 0; line-height: 1.15; }
  .sub { color: #555; font-size: 12px; margin-top: 3px; }
  h2 { font-size: 15px; margin: 18px 0 6px; padding-bottom: 4px; border-bottom: 2px solid #111; }
  table { border-collapse: collapse; width: 100%; font-size: 11px; }
  th, td { border: 1px solid #ccc; padding: 3px 5px; text-align: center; white-space: nowrap; }
  th { background: #f2f2f2; font-weight: 700; }
  td.stop, th.stop { text-align: left; font-weight: 600; position: sticky; left: 0; background: #fff; }
  .grid td.mins { text-align: left; letter-spacing: 0.3px; }
  .grid td.hour { font-weight: 800; background: #f7f7f7; width: 42px; }
  .note { font-size: 11px; color: #666; margin-top: 4px; }
  .foot { margin-top: 18px; font-size: 10px; color: #888; display: flex; justify-content: space-between; }
  .wrap { overflow-x: auto; }
  @page { size: A4 landscape; margin: 10mm; }
  @media print { .page { padding: 0; max-width: none; } .wrap { overflow: visible; } tr { page-break-inside: avoid; } h2 { page-break-after: avoid; } }
`;

const shell = ({ title, lang, dir, body }) => `<!doctype html>
<html lang="${esc(lang)}" dir="${dir}"><head><meta charset="utf-8"><title>${esc(title)}</title><meta name="viewport" content="width=device-width, initial-scale=1"><style>${CSS}</style></head><body><div class="page">${body}</div></body></html>`;

const matrixTable = (stopsInfo, trips) => {
  // Column order: trips by departure at their first stop; rows: the union of stops in pattern order (dominant pattern first).
  const order = [];
  const seen = new Set();
  const patterns = [...trips].sort((a, b) => b.stops.length - a.stops.length);
  for (const t of patterns) for (const s of t.stops) if (!seen.has(s.stop_id)) { seen.add(s.stop_id); order.push(s.stop_id); }
  const sorted = [...trips].sort((a, b) => a.stops[0].dep - b.stops[0].dep);
  const head = `<tr><th class="stop"></th>${sorted.map((t) => `<th>${esc(hhmm(t.stops[0].dep))}</th>`).join("")}</tr>`;
  const rows = order.map((sid) => `<tr><td class="stop">${esc(stopsInfo.get(sid)?.name || sid)}</td>${sorted.map((t) => { const s = t.stops.find((x) => x.stop_id === sid); return `<td>${s && s.dep != null ? esc(hhmm(s.dep)) : "·"}</td>`; }).join("")}</tr>`).join("");
  return `<div class="wrap"><table>${head}${rows}</table></div>`;
};

const gridTable = (l, stopsInfo, trips) => {
  const order = [];
  const seen = new Set();
  for (const t of [...trips].sort((a, b) => b.stops.length - a.stops.length)) for (const s of t.stops) if (!seen.has(s.stop_id)) { seen.add(s.stop_id); order.push(s.stop_id); }
  const hours = new Set();
  const perStop = new Map();
  for (const sid of order) {
    const deps = trips.map((t) => t.stops.find((x) => x.stop_id === sid)?.dep).filter((d) => d != null);
    const g = hourGrid(deps);
    perStop.set(sid, new Map(g));
    for (const [h] of g) hours.add(h);
  }
  const hs = [...hours].sort((a, b) => a - b);
  const head = `<tr><th class="stop">${esc(l.stop)}</th>${hs.map((h) => `<th>${String(h).padStart(2, "0")}h</th>`).join("")}</tr>`;
  const rows = order.map((sid) => `<tr><td class="stop">${esc(stopsInfo.get(sid)?.name || sid)}</td>${hs.map((h) => `<td class="mins">${(perStop.get(sid).get(h) || []).map((m) => String(m).padStart(2, "0")).join(" ")}</td>`).join("")}</tr>`).join("");
  return `<div class="wrap"><table class="grid">${head}${rows}</table></div>`;
};

/** HTML of a line's timetable. */
const timetableHtml = (db, { routeId, date, lang = "en" }) => {
  const l = L10N[lang] || L10N.en;
  const route = db.prepare("SELECT route_id, route_short_name, route_long_name, route_color, route_text_color, agency_id FROM routes WHERE route_id = ?").get(routeId);
  if (!route) return null;
  const agency = db.prepare("SELECT agency_name FROM agency WHERE agency_id = ? OR ? = ''").get(route.agency_id || "", route.agency_id || "") || db.prepare("SELECT agency_name FROM agency LIMIT 1").get();
  const sd = resolveServiceDate(db, date);
  const trips = dayTrips(db, sd.services, { routeId });
  const stopsInfo = new Map(db.prepare("SELECT stop_id, stop_name FROM stops").all().map((s) => [s.stop_id, { name: s.stop_name }]));
  const color = /^[0-9A-Fa-f]{6}$/.test(route.route_color || "") ? route.route_color : "1E88E5";
  const text = /^[0-9A-Fa-f]{6}$/.test(route.route_text_color || "") ? route.route_text_color : textColorFor(color);
  const title = `${l.line} ${route.route_short_name || route.route_id}${route.route_long_name ? ` — ${route.route_long_name}` : ""}`;
  let body = `<div class="head"><div class="badge" style="background:#${color};color:#${text}">${esc(route.route_short_name || route.route_id)}</div><div><h1>${esc(route.route_long_name || route.route_short_name || route.route_id)}</h1><div class="sub">${esc(agency?.agency_name || "")} · ${esc(l.timetable)} · ${esc(l.validOn)} ${esc(prettyDate(sd.date, l))}${sd.shifted ? ` (${esc(l.nextService)} ${esc(prettyDate(sd.date, l))})` : ""}</div></div></div>`;
  if (!trips.length) body += `<p class="note">${esc(l.noService)}</p>`;
  for (const dirId of ["0", "1"]) {
    const dt = trips.filter((t) => t.direction_id === dirId);
    if (!dt.length) continue;
    const headsign = [...dt.reduce((m, t) => m.set(t.headsign, (m.get(t.headsign) || 0) + 1), new Map()).entries()].sort((a, b) => b[1] - a[1])[0][0] || stopsInfo.get(dt[0].stops[dt[0].stops.length - 1].stop_id)?.name || "";
    body += `<h2>${esc(l.direction)} ${esc(headsign)} <span class="note">· ${dt.length} ${esc(l.trips)}</span></h2>`;
    body += dt.length <= MATRIX_MAX_TRIPS ? matrixTable(stopsInfo, dt) : gridTable(l, stopsInfo, dt);
  }
  body += `<div class="foot"><span>${esc(l.generated)}</span><span>${new Date().toISOString().slice(0, 10)}</span></div>`;
  return shell({ title, lang, dir: lang === "ar" ? "rtl" : "ltr", body });
};

/** HTML of a stop's departure poster. */
const stopPosterHtml = (db, { stopId, date, lang = "en" }) => {
  const l = L10N[lang] || L10N.en;
  const stop = db.prepare("SELECT stop_id, stop_name, stop_code FROM stops WHERE stop_id = ?").get(stopId);
  if (!stop) return null;
  const sd = resolveServiceDate(db, date);
  const trips = dayTrips(db, sd.services, { stopId });
  const routes = new Map(db.prepare("SELECT route_id, route_short_name, route_long_name, route_color, route_text_color FROM routes").all().map((r) => [r.route_id, r]));
  const stopsInfo = new Map(db.prepare("SELECT stop_id, stop_name FROM stops").all().map((s) => [s.stop_id, s.stop_name]));
  // Group: route + direction → departures at this stop (skip when the stop is the last one).
  const groups = new Map();
  for (const t of trips) {
    const idx = t.stops.findIndex((s) => s.stop_id === stopId);
    if (idx < 0 || idx === t.stops.length - 1 || t.stops[idx].dep == null) continue;
    const key = `${t.route_id}|${t.direction_id}`;
    const g = groups.get(key) || { route: routes.get(t.route_id) || { route_id: t.route_id, route_short_name: t.route_id }, headsigns: new Map(), deps: [], last: stopsInfo.get(t.stops[t.stops.length - 1].stop_id) };
    g.deps.push(t.stops[idx].dep);
    if (t.headsign) g.headsigns.set(t.headsign, (g.headsigns.get(t.headsign) || 0) + 1);
    groups.set(key, g);
  }
  let body = `<div class="head"><div class="badge" style="background:#111;color:#fff">${esc(l.stop)}</div><div><h1>${esc(stop.stop_name)}</h1><div class="sub">${stop.stop_code ? `${esc(stop.stop_code)} · ` : ""}${esc(l.poster)} · ${esc(l.validOn)} ${esc(prettyDate(sd.date, l))}${sd.shifted ? ` (${esc(l.nextService)} ${esc(prettyDate(sd.date, l))})` : ""}</div></div></div>`;
  if (!groups.size) body += `<p class="note">${esc(l.noService)}</p>`;
  for (const g of [...groups.values()].sort((a, b) => String(a.route.route_short_name).localeCompare(String(b.route.route_short_name), undefined, { numeric: true }))) {
    const color = /^[0-9A-Fa-f]{6}$/.test(g.route.route_color || "") ? g.route.route_color : "1E88E5";
    const text = /^[0-9A-Fa-f]{6}$/.test(g.route.route_text_color || "") ? g.route.route_text_color : textColorFor(color);
    const headsign = [...g.headsigns.entries()].sort((a, b) => b[1] - a[1])[0]?.[0] || g.last || "";
    const deps = [...new Set(g.deps)].sort((a, b) => a - b);
    body += `<h2><span class="badge" style="display:inline-flex;min-width:34px;height:26px;font-size:14px;border-radius:8px;background:#${color};color:#${text};vertical-align:middle;margin-right:8px">${esc(g.route.route_short_name || g.route.route_id)}</span>${esc(l.direction)} ${esc(headsign)} <span class="note">· ${esc(l.firstLast)} ${hhmm(deps[0])} / ${hhmm(deps[deps.length - 1])}</span></h2>`;
    const grid = hourGrid(deps);
    body += `<div class="wrap"><table class="grid"><tr><th>${esc(l.hour)}</th><th style="text-align:left">${esc(l.minutes)}</th></tr>${grid.map(([h, mins]) => `<tr><td class="hour">${String(h).padStart(2, "0")}</td><td class="mins">${mins.map((m) => String(m).padStart(2, "0")).join("  ")}</td></tr>`).join("")}</table></div>`;
  }
  body += `<div class="foot"><span>${esc(l.generated)}</span><span>${new Date().toISOString().slice(0, 10)}</span></div>`;
  return shell({ title: `${stop.stop_name} — ${l.poster}`, lang, dir: lang === "ar" ? "rtl" : "ltr", body });
};

// ── HTTP ───────────────────────────────────────────────────────────────────

const langOf = (req) => {
  const v = String(req.query?.lang || "en").slice(0, 2).toLowerCase();
  return L10N[v] ? v : "en";
};
const dateOf = (req) => {
  const v = String(req.query?.date || "").replace(/-/g, "");
  return /^\d{8}$/.test(v) ? v : todayYmd();
};

const getTimetable = (req, res) => {
  const ctx = requireSession(req, res);
  if (!ctx) return;
  const routeId = String(req.query?.route_id || "").trim();
  if (!routeId) return res.status(400).json({ error: "INVALID_INPUT", message: "route_id is required." });
  try {
    const html = timetableHtml(ctx.db, { routeId, date: dateOf(req), lang: langOf(req) });
    if (!html) return res.status(404).json({ error: "NOT_FOUND", message: "Route not found." });
    res.setHeader("Content-Type", "text/html; charset=utf-8");
    res.send(html);
  } catch (err) {
    console.error("timetable document:", err);
    res.status(500).json({ error: "DOCUMENT_FAILED", message: err.message });
  }
};

const getStopPoster = (req, res) => {
  const ctx = requireSession(req, res);
  if (!ctx) return;
  const stopId = String(req.query?.stop_id || "").trim();
  if (!stopId) return res.status(400).json({ error: "INVALID_INPUT", message: "stop_id is required." });
  try {
    const html = stopPosterHtml(ctx.db, { stopId, date: dateOf(req), lang: langOf(req) });
    if (!html) return res.status(404).json({ error: "NOT_FOUND", message: "Stop not found." });
    res.setHeader("Content-Type", "text/html; charset=utf-8");
    res.send(html);
  } catch (err) {
    console.error("stop poster document:", err);
    res.status(500).json({ error: "DOCUMENT_FAILED", message: err.message });
  }
};

module.exports = { timetableHtml, stopPosterHtml, getTimetable, getStopPoster, _internals: { hourGrid, dayTrips, resolveServiceDate, L10N } };
